### ISSUE TITLE
Duplicate Functionality

### ISSUE THREAD

**Issue by nickarnold** [jsonxr/node-mongo-randomid#1]
Hey Jason! I was checking out your Github account last night and noticed you needed to generate random ObjectIDs for Mongo. I've also thought about this problem before in a slightly different context and found that the `uuid` module can be leveraged to generate a very good random type-4 UUID. With a little string manipulation and some npm usage I created a module that generates a 24 character ObjectID without the sequential problem inherent with repeated calls to `new MongoID()`. It's called [mongo-roid](https://github.com/nickarnold/mongo-roid) and is currently [published to npm](https://www.npmjs.com/package/mongo-roid).

Also, I made explicit use of `npm shrinkwrap` to solidify the lesson from the other day...

Cheers.

**Comment by jsonxr** [comment]
Thanks nick. This provides a drop in replacement for the ObjectId provided in mongoose.  It overrides the generate prototype of the ObjectId provided in the bson package which mongoose uses. This also preserves the timestamp feature which is helpful in certain cases for sharding or sorting.
